version: "3.9"

services:
  redis_myresume:
    container_name: redis_myresume
    image: redis
    restart: always
    ports:
      - "6380:6379"  # Updated port mapping
    command: redis-server --save 60 1 --loglevel warning

  postgresql_myresume:
    image: postgres:latest
    container_name: postgresql_myresume
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5434:5432"

  backend_myresume:
    build: .
    container_name: backend_myresume
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app/
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    depends_on:
      - postgres_myresume
      - redis_myresume


volumes:
  static_volume:
  media_volume: