# Generated by Django 4.2.2 on 2023-11-04 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_information_create_date_information_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(default='website/defualt.jpg', upload_to='website/%y/'),
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_more', models.ImageField(default='website/defualt.jpg', upload_to='website/%y/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.information')),
            ],
        ),
    ]
