# Generated by Django 4.2.2 on 2023-11-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_userimage_create_date_userimage_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
