# Generated by Django 4.2.2 on 2023-11-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_skill_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image_more',
            field=models.ImageField(default='website/defualt.jpg', upload_to='website'),
        ),
    ]
