# Generated by Django 4.2.2 on 2023-11-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_setting_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
