# Generated by Django 4.2.6 on 2023-11-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_professionalexperience_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='message',
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='message',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
