# Generated by Django 4.2.6 on 2023-11-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_education_status_professionalexperience_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='about_my_resume',
            field=models.TextField(null=True),
        ),
    ]
