# Generated by Django 4.2.6 on 2023-11-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_information_about_my_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='age',
        ),
    ]
