# Generated by Django 4.2.2 on 2023-11-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='git',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
