# Generated by Django 4.2.2 on 2023-07-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_created_data_contact_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date']},
        ),
    ]
