# Generated by Django 4.2.2 on 2023-11-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_information_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='about_me',
            field=models.TextField(default=23),
            preserve_default=False,
        ),
    ]
