# Generated by Django 4.2.2 on 2023-11-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_information_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='my_words',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
