# Generated by Django 4.2.2 on 2023-11-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_information_my_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='my_words',
            new_name='my_works',
        ),
    ]
