# Generated by Django 4.2.2 on 2023-11-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_information_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='job',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
