# Generated by Django 4.2.2 on 2023-11-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_information_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
