# Generated by Django 4.2.2 on 2023-11-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_skill_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.TextField(),
        ),
    ]
