# Generated by Django 4.2.2 on 2023-11-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_userimage_image_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(default='website/defualt.jpg', upload_to='website'),
        ),
    ]
