# Generated by Django 4.2.2 on 2023-11-07 14:25

from django.db import migrations, models
import mysite.tools


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_information_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(default='website/defualt.jpg', upload_to=mysite.tools.UploadToPathAndRename('website')),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image_more',
            field=models.ImageField(default='website/defualt.jpg', upload_to=mysite.tools.UploadToPathAndRename('website')),
        ),
    ]
