# Generated by Django 4.2.6 on 2023-11-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_remove_information_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetter',
        ),
    ]
