# Generated by Django 4.2.2 on 2023-09-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_relation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
