# Generated by Django 4.2.2 on 2023-10-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='University',
            new_name='job',
        ),
    ]
