# Generated by Django 4.2.2 on 2023-10-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_university_profileuser_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
