# Generated by Django 4.2.2 on 2023-09-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_slug_alter_post_author_voteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/defualt.jpg', upload_to='blog/%y/%m/%d/'),
        ),
    ]
