# Generated by Django 4.2.2 on 2023-11-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default='blog/defualt.jpg', upload_to='blog/%y/'),
        ),
    ]
