# Generated by Django 4.2.2 on 2023-11-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='post',
            name='modify_date',
        ),
    ]
