# Generated by Django 4.2.2 on 2023-11-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_create_date_post_is_active_post_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about',
            field=models.CharField(default='reza', max_length=200),
        ),
    ]
