# Generated by Django 4.2.2 on 2023-11-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_remove_comment_email_remove_comment_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_date',)},
        ),
    ]
