# Generated by Django 4.2.2 on 2023-11-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
